---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common'] 

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Make sure destination directory exists
      file:
        path: /root/.docker/
        state: directory
        recurse: yes
        
    - name: Deploying the registry credentials we created
      copy:
        src: .cred
        dest: /root/.docker/config.json

    - name: Deploying a systemd service that will create the container
      copy:
        src: .service
        dest: /etc/systemd/system/iktos.service

    - name: Starts the service 
      systemd: name=iktos.service state=restarted enabled=yes